---
- name: Assure latest package requirements
  apt: name={{ item }} update_cache={{ update_pkg_cache }} state=latest
  with_items: django_latest_packages
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_pkg_cache }} force=yes state=installed
  with_items: django_base_packages
  tags: packages

- name: Install pip latest packages
  pip: name={{ item }}
  with_items: django_pip_packages
  tags: packages

- name: Install specific versioned pip packages
  pip: name={{ item.name }} version={{ item.version}}
  with_items: django_pip_versioned_packages
  tags: packages
