---
- name: create downloads directory
  file:
    dest: "{{ supervio_downloads_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755

- name: (Re)Generate site-available ui config
  template:
    src: "etc/apache2/sites-available/{{ supervio_django_app }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ supervio_django_app }}.conf"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

- name: (Re)Generate site-available download config
  template:
    src: "etc/apache2/sites-available/{{ supervio_django_app }}-downloads.conf.j2"
    dest: "/etc/apache2/sites-available/{{ supervio_django_app }}-downloads.conf"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644
  tags:
    - downloads

- name: enable the general supervio site (this is not the supervio-ui)
  command: "a2ensite {{ supervio_django_app }}-downloads"
  tags:
    - downloads
