---
- name: create downloads directory
  file:
    dest: "{{ supervio_downloads_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755

- name: get depot file stats
  stat: path="{{ supervio_downloads_dir }}/{{ supervio_depot_zip }}"
  when: supervio_download_files
  register: depot
  tags:
    - downloads

- name: pull depot files for future downloads (may take many minutes)
  get_url:
    force: yes
    dest: "{{ supervio_downloads_dir }}/{{ supervio_depot_zip }}"
    url: "{{ supervio_depot_zip_url }}"
    timeout: "{{ supervio_downloads_timeout }}"
  when: supervio_download_files and (not depot.stat.exists or (depot.stat.md5 != "{{ supervio_depot_zip_md5 }}"))
  tags:
    - downloads

- name: get NSX OVA stats
  stat: path="{{ supervio_downloads_dir }}/{{ supervio_nsx_ova }}"
  register: nsxova
  when: supervio_download_files
  tags:
    - downloads

- name: pull NSX OVA for future downloads (may take many minutes)
  get_url:
    force: yes
    dest: "{{ supervio_downloads_dir }}/{{ supervio_nsx_ova }}"
    url: "{{ supervio_nsx_ova_url }}"
    timeout: "{{ supervio_downloads_timeout }}"
  when: supervio_download_files and (not nsxova.stat.exists or (nsxova.stat.md5 != "{{ supervio_nsx_ova_md5 }}"))
  tags:
    - downloads

- name: get VIO OVA file stats
  stat: path="{{ supervio_downloads_dir }}/{{ supervio_vio_ova }}"
  register: vioova
  when: supervio_download_files
  tags:
    - downloads

- name: pull VIO OVA for future downloads (may take many minutes)
  get_url:
    force: yes
    dest: "{{ supervio_downloads_dir }}/{{ supervio_vio_ova }}"
    url: "{{ supervio_vio_ova_url }}"
    timeout: "{{ supervio_downloads_timeout }}"
  when: supervio_download_files and (not vioova.stat.exists or (vioova.stat.md5 != "{{ supervio_vio_ova_md5 }}"))
  tags:
    - downloads

- name: get OVFTool zip file stats
  stat: path="{{ supervio_downloads_dir }}/{{ supervio_ovftool_zip }}"
  register: ovftool
  when: supervio_download_files
  tags:
    - downloads

- name: pull OVFTool for future downloads (may take many minutes)
  get_url:
    force: yes
    dest: "{{ supervio_downloads_dir }}/{{ supervio_ovftool_zip }}"
    url: "{{ supervio_ovftool_url }}"
    timeout: "{{ supervio_downloads_timeout }}"
  when: supervio_download_files and (not ovftool.stat.exists or (ovftool.stat.md5 != "{{ supervio_ovftool_md5 }}"))
  tags:
    - downloads

- name: get esx hypervisor iso file stats
  stat: path="{{ supervio_downloads_dir }}/{{ supervio_esxi_iso }}"
  register: esxiiso
  tags:
    - downloads

- name: pull esxi iso for future downloads (may take many minutes)
  get_url:
    dest: "{{ supervio_downloads_dir }}/{{ supervio_esxi_iso }}"
    url: "{{ supervio_esxi_url }}"
    timeout: "{{ supervio_downloads_timeout }}"
  when: supervio_download_files and not (esxiiso.stat.exists and (esxiiso.stat.md5 == "{{ supervio_esxi_md5 }}"))
  tags:
    - downloads

- name: (Re)Generate site-available supervio-ui config
  template:
    src: "etc/apache2/sites-available/{{ supervio_django_app }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ supervio_django_app }}.conf"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

- name: (Re)Generate site-available supervio-download config
  template:
    src: "etc/apache2/sites-available/{{ supervio_django_app }}-downloads.conf.j2"
    dest: "/etc/apache2/sites-available/{{ supervio_django_app }}-downloads.conf"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644
  tags:
    - downloads

- name: enable the general supervio site (this is not the supervio-ui)
  command: "a2ensite {{ supervio_django_app }}-downloads"
  tags:
    - downloads
