---
- name: create supervio directory
  file:
    dest: "/opt/{{ supervio_django_app }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: create blackhole directory
  file:
    dest: "/opt/{{ supervio_django_app }}/.blackhole"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: recursively sync the ui code from local repos
  synchronize: src=../../../ui/ dest=/opt/{{ supervio_django_app }}/ recursive=yes rsync_opts=--no-motd,--exclude=.git
  tags:
    - rsync

- name: ensure ansible plays directory exists
  file:
    dest: "/opt/{{ supervio_django_app }}-ansible"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: recursively sync the ansible playbooks from local repos
  synchronize: src=../../../ansible/playbooks dest=/opt/{{ supervio_django_app }}-ansible/ recursive=yes rsync_opts=--no-motd,--exclude=.git
  tags:
    - rsync
- name: recursively sync the ansible roles from local repos
  synchronize: src=../../../ansible/roles dest=/opt/{{ supervio_django_app }}-ansible/ recursive=yes rsync_opts=--no-motd,--exclude=.git
  tags:
    - rsync
- name: recursively sync the ansible library from local repos
  synchronize: src=../../../ansible/library dest=/opt/{{ supervio_django_app }}-ansible/ recursive=yes rsync_opts=--no-motd,--exclude=.git
  tags:
    - rsync

- name: recursively sync the containers built by ansible from local repos
  synchronize: src=../../../containers dest=/opt/ recursive=yes rsync_opts=--no-motd,--exclude=.git
  tags:
    - rsync

- name: create playbook convenience script
  template:
    src: "opt/{{ supervio_django_app }}/{{ supervio_django_app }}_play.j2"
    dest: "/opt/{{ supervio_django_app }}/{{ supervio_django_app }}_play"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "0700"
  tags:
    - rsync

- name: create playbook convenience script for tags
  template:
    src: "opt/{{ supervio_django_app }}/{{ supervio_django_app }}_play_tags.j2"
    dest: "/opt/{{ supervio_django_app }}/{{ supervio_django_app }}_play_tags"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "0700"
  tags:
    - rsync

- name: create custom variables script
  template:
    src: "opt/{{ supervio_django_app }}/prepare_variables.py.j2"
    dest: "/opt/{{ supervio_django_app }}/prepare_variables.py"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "0700"
  tags:
    - rsync

- name: Create settings.py
  template:
    src: "opt/{{ supervio_django_app }}/{{ supervio_django_app }}/settings.py.j2"
    dest: "/opt/{{ supervio_django_app }}/supervio/settings.py"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart apache2
  tags:
    - rsync

- name: Create local_settings.py
  template:
    src: "opt/{{ supervio_django_app }}/{{ supervio_django_app }}/local_settings.py.j2"
    dest: "/opt/{{ supervio_django_app }}/supervio/local_settings.py"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart apache2
  tags:
    - rsync

- name: Create supervio working directory
  file:
    dest: "/var/lib/{{ supervio_django_app }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create base.yml
  template:
    src: "var/lib/{{ supervio_django_app }}/base.yml.j2"
    dest: "/var/lib/{{ supervio_django_app }}/base.yml"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart apache2
  tags:
    - rsync

- name: Create Answer files directory
  file:
    dest: "{{ supervio_answer_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create Prepare files directory
  file:
    dest: "{{ supervio_prepare_files_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create Logs directory
  file:
    dest: "{{ supervio_log_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create database
  command: touch "/opt/{{ supervio_django_app }}/{{ supervio_django_app }}.db"
  args:
    creates: "/opt/{{ supervio_django_app }}/{{ supervio_django_app }}.db"
  sudo: no
  register: db

- name: Initialize database
  command: python manage.py syncdb --noinput
  args:
    chdir: "/opt/{{ supervio_django_app }}"
  sudo: no
  when: db.changed

- name: Disable 000-default site
  command: a2dissite 000-default
  notify: Restart apache2
  tags:
    - rsync

- name: Enable supervio site
  command: a2ensite {{ supervio_django_app }}
  notify: Restart apache2
  tags:
    - rsync
