---
- name: create supervio directory
  file:
    dest: "/opt/{{ supervio_django_app }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: create blackhole directory
  file:
    dest: "/opt/{{ supervio_django_app }}/.blackhole"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: recursively sync the ui code from local repos
  command: "rsync -a --recursive --no-motd --exclude=.git ui/ {{ rsync_user_id }}@{{ inventory_hostname }}:/opt/{{ supervio_django_app }}/"
  args:
    chdir: ../../..
  sudo: no
  delegate_to: localhost
  tags:
    - rsync

- name: ensure ansible plays directory exists
  file:
    dest: "/opt/{{ supervio_django_app }}-ansible"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: recursively sync the ansible roles from local repos
  command: "rsync -a --recursive --no-motd --exclude=.git ansible/roles ansible/library {{ rsync_user_id }}@{{ inventory_hostname }}:/opt/{{ supervio_django_app }}-ansible/"
  args:
    chdir: ../../..
  sudo: no
  delegate_to: localhost
  tags:
    - rsync

- name: Create local_settings.py
  template:
    src: "opt/{{ supervio_django_app }}/{{ supervio_django_app }}/local_settings.py.j2"
    dest: "/opt/{{ supervio_django_app }}/supervio/local_settings.py"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart apache2
  tags:
    - rsync

- name: Create supervio working directory
  file:
    dest: "/var/lib/{{ supervio_django_app }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create base.yml
  template:
    src: "var/lib/{{ supervio_django_app }}/base.yml.j2"
    dest: "/var/lib/{{ supervio_django_app }}/base.yml"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart apache2
  tags:
    - rsync

- name: Create Answer files directory
  file:
    dest: "{{ supervio_answer_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create Prepare files directory
  file:
    dest: "{{ supervio_prepare_files_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create Logs directory
  file:
    dest: "{{ supervio_log_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create database
  command: touch "/opt/{{ supervio_django_app }}/{{ supervio_django_app }}.db"
  args:
    creates: "/opt/{{ supervio_django_app }}/supervio.db"
  sudo: no
  register: db

- name: Initialize database
  command: python manage.py syncdb --noinput
  args:
    chdir: "/opt/{{ supervio_django_app }}"
  sudo: no
  when: db.changed

- name: Disable 000-default site
  command: a2dissite 000-default
  notify: Restart apache2
  tags:
    - rsync

- name: Enable supervio site
  command: a2ensite {{ supervio_django_app }}
  notify: Restart apache2
  tags:
    - rsync
